# This is a basic workflow to help you get started with Actions

name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-GHARunner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
