# This is a basic workflow to help you get started with Actions

name: Hello World
on: [push]
jobs:
  StepOne:
    runs-on:
      - codebuild-GHARunner-${{ github.run_id }}-${{ github.run_attempt }}
    environment: Dev
    steps:
      - run: echo "This is Step 1"
  StepTwo:
    runs-on:
      - codebuild-GHARunnerStageTwo-${{ github.run_id }}-${{ github.run_attempt }}
    environment: Dev
    steps:
      - run: echo "This is Step 2. GH_CONTEXT: $GITHUB_CONTEXT | JOB_CONTEXT: $JOB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}

